#
#  Robot allocation strategy
#
#  Format:
#
#    host:
#      - robot[:lane[:instances]]
#
#  where
#    1. robot is a single robot identifier (fully-qualified with
#       REPO_SUITE_ROBOT, e.g., "dor_accessionWF_technical-metadata").
#    2. lane is 
#          - a single identifier ('A'), or 
#          - a list of identiers ('A,B,C'), or 
#          - an asterix (*).
#    3. instances is a single integer.
#
#  Both lane and instances are optional. Lane defaults to 'default', and 
#  instances defaults to 1.
#
#  When a robot is allocated to multiple lanes, it reads them in
#  PRIORITY ORDER. That is, if a robot is listening to lanes A, B, and C,
#  it works on lane A until empty, then lane B until empty, and then
#  lane C until empty. In the meantime, if a job comes in on a 'faster'
#  lane, it works on that after finishing it's current job (i.e., after
#  working on a job in lane C, if a job comes in on lane A in the intermin,
#  the robot will work on the lane A job next before returning to lane C).
#  When using an asterix for the lane designator, the lanes are processed
#  in alphabetical order.
#
#  Note that the syntax is YAML, so the lists must not contain spaces or
#  needs to be quoted.
#  
#    RIGHT
#      - dor_accessionWF_technical-metadata:A:5
#      - 'dor_accessionWF_technical-metadata : A : 5'
#
#    WRONG
#      - dor_accessionWF_technical-metadata : A : 5
#      - dor_accessionWF_technical-metadata: A: 5
#

geomdtk-dev:
  - dor_gisAssemblyWF_approve-data
  - dor_gisAssemblyWF_approve-metadata
  - dor_gisAssemblyWF_assign-placenames
  - dor_gisAssemblyWF_author-data
  - dor_gisAssemblyWF_author-metadata
  - dor_gisAssemblyWF_extract-iso19139
  - dor_gisAssemblyWF_extract-thumbnail
  - dor_gisAssemblyWF_finish-data
  - dor_gisAssemblyWF_finish-gis-assembly-workflow
  - dor_gisAssemblyWF_finish-metadata
  - dor_gisAssemblyWF_generate-content-metadata
  - dor_gisAssemblyWF_generate-geo-metadata
  - dor_gisAssemblyWF_generate-mods
  - dor_gisAssemblyWF_normalize-data
  - dor_gisAssemblyWF_package-data
  - dor_gisAssemblyWF_register-druid
  - dor_gisAssemblyWF_start-assembly-workflow
  - dor_gisAssemblyWF_start-delivery-workflow
  - dor_gisAssemblyWF_wrangle-data
  - dor_gisDeliveryWF_finish-gis-delivery-workflow
  - dor_gisDeliveryWF_load-geoserver
  - dor_gisDeliveryWF_load-geowebcache
  - dor_gisDeliveryWF_load-raster
  - dor_gisDeliveryWF_load-vector
  - dor_gisDeliveryWF_seed-geowebcache
  - dor_gisDeliveryWF_start-gis-discovery-workflow
  - dor_gisDiscoveryWF_finish-gis-discovery-workflow
  - dor_gisDiscoveryWF_generate-geosearch
  - dor_gisDiscoveryWF_generate-ogp
  - dor_gisDiscoveryWF_load-geosearch
  - dor_gisDiscoveryWF_load-ogp
